version: '3.8'

services:
    server: 
        build: 
            context: ./
            target: development-build-stage
            dockerfile: Dockerfile
        container_name: server
        ports:
            - '3000:3000'   
        volumes:
        - ./:/app
        - /app/node_modules

    mongo:
        image: mongo
        volumes:
            - mongo-data:/data/db

volumes:
    mongo-data:
