name: CD

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Copy .env file
              run: echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push Docker image
              run: |
                  docker build -t ${{ secrets.DOCKER_USERNAME }}/online-courses-api:latest .
                  docker push ${{ secrets.DOCKER_USERNAME }}/online-courses-api:latest

            - name: Deploy to EC2
              uses: appleboy/ssh-action@v0.1.3
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_KEY }}
                  port: 22
                  script: |
                      docker pull ${{ secrets.DOCKER_USERNAME }}/online-courses-api:latest
                      docker rm -f online-courses-container || true
                      docker run -d -p 8080:8080 --env-file .env --name online-courses-container ${{ secrets.DOCKER_USERNAME }}/online-courses-api:latest
                      sudo cp /home/ubuntu/nginx.conf /etc/nginx/nginx.conf
                      sudo systemctl restart nginx
