name: CI Pipeline

on:
    push:
        branches: ['main']

jobs:
    build:
        runs-on: self-hosted

        steps:
            - uses: actions/checkout@v3
            - name: Login Dockerhub
              env:
                  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
                  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
              run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

            - name: Build the Docker image
              run: docker build -t sukablyat007/online-courses-api .
            - name: Push to Dockerhub
              run: docker push sukablyat007/online-courses-api:latest
