name: CICD

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: [ubuntu-latest]
        steps:
            - name: Checkout source
              uses: actions/checkout@v3
            - name: Login to docker hub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            - name: Build docker image
              run: docker build -t sukablyat007/online-courses-api .
            - name: Publish image to docker hub
              run: docker push sukablyat007/online-courses-api:latest

    deploy:
        needs: build
        runs-on: [aws-ec2]
        steps:
            - name: Pull image from docker hub
              run: docker pull sukablyat007/online-courses-api:latest
            - name: Delete old container
              run: docker rm -f online-courses-container
            - name: Run docker container
              run: docker run -d -p 5000:5000 --name online-courses-container sukablyat007/online-courses-api
