name: CI/CD

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: [ubuntu-latest]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push Docker image
              run: |
                  docker build -t ${{ secrets.DOCKER_USERNAME }}/online-courses-api .
                  docker push ${{ secrets.DOCKER_USERNAME }}/online-courses-api:latest

            # - name: Deploy to EC2 instance
            #   env:
            #       IMAGE_NAME: online-courses-api # Thay bằng tên image Docker của bạn
            #       EC2_HOST: ${{ secrets.EC2_HOST }}
            #       EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
            #   run: |
            #       ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_HOST << EOF
            #         docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/$IMAGE_NAME:${{ github.sha }}
            #         docker stop $(docker ps -a -q)
            #         docker rm $(docker ps -a -q)
            #         docker run -d -p 80:3000 ${{ secrets.DOCKER_HUB_USERNAME }}/$IMAGE_NAME:${{ github.sha }}
            #       EOF
    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Pull image from docker hub
              run: docker pull sukablyat007/online-courses-api:latest
            - name: Delete old container
              run: docker rm -f online-courses-api
            - name: Run Docker Container
              run: docker run -d -p 8000:8000 --name online-courses-api sukablyat007/online-courses-api
